### ISSUE TITLE
CERN points latest deb release to out-of-date version

### ISSUE THREAD

**Issue by tpdownes** [cvmfs-contrib/cvmfs-contrib.github.io#1]
The file `https://ecsft.cern.ch/dist/cvmfs/cvmfs-contrib-release/cvmfs-contrib-release-latest_all.deb` appears to point to version `1.4.1` of the release package while the latest release is `1.6.1`. This is not a major problem *right now* as the installation of the former will eventually upgrade to the latter, but it might reflect a problem with scripts that update `latest` at CERN.

**Comment by DrDaveD** [comment]
Hi Tom, could you please create this as a CVM JIRA ticket?

**Comment by DrDaveD** [comment]
On second thought, maybe @jblomer prefers to just keep this here.

**Comment by tpdownes** [comment]
I will do as @jblomer requests.

**Comment by jblomer** [comment]
For the cvmfs-contrib packages, I'd prefer to have the issue tracking on github.
